config/routes.rb
Maps::Application.routes.draw do
  get "ashdown/index"

  get "split/index"

  root to: "taylor#index"

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/ashdown_controller.rb
class AshdownController < ApplicationController
  def index
  end
end

app/controllers/taylor_controller.rb
class TaylorController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def opening_para
    return "Southwest Arkansas Planning and Developement Districts Water and Sewer system Mapping program"
  end
end

app/helpers/ashdown_helper.rb
module AshdownHelper
end

app/helpers/taylor_helper.rb
module TaylorHelper
end

app/views/ashdown/index.html.erb
<h1>Ashdown#index</h1>
<p>Find me in app/views/ashdown/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Maps</title>
  <%= stylesheet_link_tag    "bootstrap",'taylor', :media => "all" %>
  <link rel="stylesheet" href="http://js.arcgis.com/3.7/js/esri/css/esri.css">
  <%= javascript_include_tag 'jquery',"bootstrap" %>
  <script src="http://js.arcgis.com/3.7/"></script>
  <%= csrf_meta_tags %>
  <script>
    var map,
    	webmapId = "7cadf9c55627415b9f11f44232866e85";
    require([
	        
    		"esri/map",
    		"esri/arcgis/utils",
    		"esri/dijit/Legend",
    		"esri/dijit/HomeButton",
    		"dojo/domReady!"], function(Map, arcgisUtils, Legend, HomeButton) {
      arcgisUtils.createMap(webmapId, "mapDiv").then(function(response){
      	map = response.map
      	
      	var legend = new Legend({
            map: map,
            layerInfos:(arcgisUtils.getLegendLayers(response))
        }, "legendDiv");
        
        legend.startup();
        
        var home = new HomeButton({
        map: map
      	}, "HomeButton");
      
      	home.startup();
      });
    });
  </script>
</head>
<body>
		<div class="wrapper">
			<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
			  <!-- Brand and toggle get grouped for better mobile display -->
			  <div class="navbar-header">
			    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
			      <span class="sr-only">Toggle navigation</span>
			      <span class="icon-bar"></span>
			      <span class="icon-bar"></span>
			      <span class="icon-bar"></span>
			    </button>
			    <a class="navbar-brand" href="#">SWAPDD</a>
			  </div>
			
			  <!-- Collect the nav links, forms, and other content for toggling -->
			  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
			    <ul class="nav navbar-nav">
			      <li class="active"><%=link_to 'Home', root_path %></li>
			    </ul>
			    <ul class="nav navbar-nav navbar-right">
			      <li><a href="#">Contact Us</a></li>
			    </ul>
			  </div><!-- /.navbar-collapse -->
			</nav>
			
			<div class="jumbotron">
			  <h1>SWAPDD GIS</h1>
			  <p><%= opening_para%></p>
			  <button class="btn btn-info btn-lg" data-toggle="modal" data-target="#myModal">
				  Learn More
				</button>
				
				<!-- Modal -->
				<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
				  <div class="modal-dialog">
				    <div class="modal-content">
				      <div class="modal-header">
				        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
				        <h4 class="modal-title" id="myModalLabel">Water &amp; Sewer Mapping Program</h4>
				      </div>
				      <div class="modal-body">
				        Description of the program here
				      </div>
				      <div class="modal-footer">
				        <button type="button" class="btn btn-primary" data-dismiss="modal">Close</button>
				      </div>
				    </div><!-- /.modal-content -->
				  </div><!-- /.modal-dialog -->
				</div><!-- /.modal -->
			</div>
			<div class="container">
			<section class="col-md-4 ">
				<%= yield %>
			</div>
			</div>
		</div>
		<footer class="col-xs-12 jumbotron">
			<address>
			  <strong>SWAPDD, Inc.</strong><br>
			  101 Harvey Couch Blvd<br>
			  Magnolia, AR 71753<br>
			  <abbr title="Phone">P:</abbr> (870) 235-4030
			</address>
			
			<address>
			  <strong>Andre' Jones</strong> GIS Tech<br>
			  <a href="mailto:#">first.last@example.com</a>
			</address>
		</footer>
	
</body>
</html>

app/views/taylor/index.html.erb
	
	<hgroup>
		<h1>
			Taylor, <small>Arkansas</small>
		</h1>
	</hgroup><hr>
	
	<h2>Legend</h2>
	<div class="col-xs-12" id="legendDiv"></div>
	<div class="col-xs-12">
		<ul class="nav nav-pills nav-stacked">
		  <li><%=link_to 'Ashdown', ashdown_index_path %></li>
		  <li><a href="#">Foreman</a></li>
		  <li class="active"><%=link_to 'Taylor', root_path %></li>
		</ul>
	</div>
</section><!-- end of div started in the app layout -->
<div class="col-md-8" id="fullHeight">
	<div id="mapDiv" class="map">
		<div id="HomeButton"></div>
	</div>
	


		
